name: Build and Deploy VitePress

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Prepare VitePress config
        env: # Or as an environment variable
          SQL_API_KEY: ${{ secrets.SQL_API_KEY }}
        run: |
          mkdir -p .vitepress
          rm *.md          
          node genmarkdownV2.js
          cp config.mts .vitepress/config.mts

      - name: Build VitePress site
        run: npx vitepress build

      - name: Copy CNAME for GitHub Pages
        run: cp CNAME .vitepress/dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
